In [1]:
import pandas as pd #for loading the dataset

In [2]:
dataset = pd.read_csv('cardio_dataset.csv').values #load the dataset into a numpy array

In [3]:
print(dataset[:10]) #first 10 entries of the dataset

[[  2.   48.  236.   66.    0.    2.    0.    1.1]
 [  1.   48.  260.   51.    0.    2.    1.    7. ]
 [  1.   44.  187.   49.    1.    2.    0.    7. ]
 [  2.   42.  216.   57.    1.    2.    0.    0.4]
 [  2.   56.  156.   42.    0.    2.    0.    2.2]
 [  1.   44.  162.   57.    1.    2.    0.    3. ]
 [  1.   50.  244.   47.    0.    2.    0.    4.2]
 [  1.   48.  212.   30.    1.    2.    0.   17.4]
 [  2.   66.  202.   53.    0.    2.    1.   13.4]
 [  1.   63.  186.   46.    1.    2.    0.   17.3]]


In [4]:
data = dataset[:,0:7] #all rows and columns from 0 to 6
target = dataset[:,7] #all rows and 7th column
print(dataset.shape)

(6644, 8)


In [5]:
from sklearn.model_selection import train_test_split
train_data,test_data,train_target,test_target = train_test_split(data,target,test_size=0.2)
from sklearn.linear_model import LinearRegression
model = LinearRegression() #Loading the algorithm
model.fit(train_data,train_target)
predicted_target = model.predict(test_data)


In [6]:
from sklearn.metrics import r2_score
r2 = r2_score(test_target,predicted_target)
print("r2: ",r2)

r2:  0.7540791656421939


In [7]:
import joblib
joblib.dump(model,'heart_risk_prediction_regression_model.sav')

['heart_risk_prediction_regression_model.sav']

#Using Feature Engineering

In [9]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
train_data_new = sc.fit_transform(train_data)

test_data_new = sc.transform(test_data)


model.fit(train_data_new,train_target)
predicted_target_new = model.predict(test_data_new)
from sklearn.metrics import r2_score
r2_new = r2_score(test_target,predicted_target_new)
print("r2: ",r2_new)

r2:  0.7540791656421939


#Using Deep Learning


In [10]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [11]:
X = dataset[:,0:7] #all rows and columns from 0 to 6
y = dataset[:,7]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [23]:
# Building the ANN
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='linear'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
167/167 [==============================] - 1s 2ms/step - loss: -83.0548 - accuracy: 0.0066
Epoch 2/50
167/167 [==============================] - 0s 2ms/step - loss: -160.1035 - accuracy: 0.0088
Epoch 3/50
167/167 [==============================] - 0s 2ms/step - loss: -173.1897 - accuracy: 0.0088
Epoch 4/50
167/167 [==============================] - 0s 2ms/step - loss: -175.2568 - accuracy: 0.0088
Epoch 5/50
167/167 [==============================] - 0s 2ms/step - loss: -176.6001 - accuracy: 0.0088
Epoch 6/50
167/167 [==============================] - 0s 2ms/step - loss: -176.9866 - accuracy: 0.0088
Epoch 7/50
167/167 [==============================] - 0s 2ms/step - loss: -177.1124 - accuracy: 0.0088
Epoch 8/50
167/167 [==============================] - 0s 2ms/step - loss: -177.1131 - accuracy: 0.0088
Epoch 9/50
167/167 [==============================] - 0s 2ms/step - loss: -177.1137 - accuracy: 0.0088
Epoch 10/50
167/167 [==============================] - 0s 2ms/step - loss:

In [24]:
y_pred = ann.predict(X_test)
from sklearn.metrics import r2_score
r2_new = r2_score(y_test, y_pred)
print("r2: ",r2_new)

r2:  -0.6032533716067996
